version: "3.8"
services:
  investryx_dev_webserver:
    container_name: investryx_dev_webserver
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/investryx-nginx-dev:latest
    ports:
      - "8080:80"  # Changed port to avoid conflicts with production
      - "8443:443"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - investryx_dev_network
    depends_on:
      - investryx_dev_backend
    # volumes:
    #   - /etc/letsencrypt:/etc/letsencrypt
    #   - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf  # Added for dev configuration
    #   - ./logs/nginx:/var/log/nginx  # Added for easier debugging
    env_file:
      - .env.dev  # Using dev environment file

  investryx_dev_backend:
    container_name: investryx_dev_backend
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/investryx-backend-dev:latest
    command: >
      /app/venv/bin/gunicorn smerger.wsgi:application
      --bind 0.0.0.0:8000
      --workers 2  # Reduced for development
      --threads 2  # Reduced for development
      --worker-class sync
      --max-requests 100  # Reduced for development
      --max-requests-jitter 20
      --timeout 120
      --keep-alive 5
      --reload  # Added for development auto-reload
    # volumes:
    #   - .:/app  # Added for hot-reload
    #   - ./logs/backend:/app/logs  # Added for easier debugging
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.dev
    depends_on:
      - investryx_dev_redis
    networks:
      - investryx_dev_network
    ports:
      - "9000:8000"  # Exposed for direct access during development

  investryx_dev_redis:
    container_name: investryx_dev_redis
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/investryx-redis-dev:latest
    command: redis-server --appendonly yes
    networks:
      - investryx_dev_network
    ports:
      - "6380:6379"  # Exposed for development debugging
    volumes:
      - redis_dev_data:/data  # Added for development persistence

  investryx_dev_uvicorn:
    container_name: investryx_dev_uvicorn
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/investryx-backend-dev:latest
    command: >
      /app/venv/bin/gunicorn smerger.asgi:application
      --bind 0.0.0.0:8001
      --workers 2  # Reduced for development
      --worker-class uvicorn.workers.UvicornWorker
      --timeout 300
      --keep-alive 65
      --reload  # Added for development auto-reload
    # volumes:
    #   - .:/app  # Added for hot-reload
    #   - ./logs/uvicorn:/app/logs  # Added for easier debugging
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env.dev
    depends_on:
      - investryx_dev_backend
      - investryx_dev_redis
    networks:
      - investryx_dev_network
    ports:
      - "9001:8001"  # Exposed for development debugging

  investryx_dev_migrate_db:
    container_name: investryx_dev_migrate_db
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/investryx-backend-dev:latest
    command: >
      bash -c "
      /app/venv/bin/python3 manage.py makemigrations --noinput &&
      /app/venv/bin/python3 manage.py migrate auth &&
      /app/venv/bin/python3 manage.py migrate contenttypes &&
      /app/venv/bin/python3 manage.py migrate admin &&
      /app/venv/bin/python3 manage.py migrate sessions &&
      /app/venv/bin/python3 manage.py migrate --noinput &&
      /app/venv/bin/python3 manage.py createcachetable
      "
    env_file:
      - .env.dev
    volumes:
   #   - .:/app  # Added for development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - investryx_dev_backend
    networks:
      - investryx_dev_network

  investryx_dev_migrate_setup:
    container_name: investryx_dev_migrate_setup
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/investryx-backend-dev:latest
    command: >
      bash -c "
      /app/venv/bin/python3 manage.py create_superuser &&
      /app/venv/bin/python3 manage.py collectstatic --noinput &&
      /app/venv/bin/python3 manage.py loaddata initial_dev_data.json  # Added for development data
      "
    env_file:
      - .env.dev
    volumes:
  #    - .:/app  # Added for development
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - investryx_dev_migrate_db
    networks:
      - investryx_dev_network

networks:
  investryx_dev_network:
    driver: bridge

volumes:
  redis_dev_data:  # Added for development data persistence