# Generated by Django 5.1.3 on 2025-05-26 09:17

import custom_storages
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smerg_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_msg', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('unread_messages_first', models.IntegerField(default=0)),
                ('unread_messages_second', models.IntegerField(default=0)),
                ('first_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_person', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='smerg_app.saleprofiles')),
                ('second_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_person', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, db_collation='utf8mb4_unicode_ci', null=True)),
                ('audio', models.FileField(blank=True, null=True, storage=custom_storages.MediaStorage(), upload_to='chat/records/')),
                ('duration', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, storage=custom_storages.MediaStorage(), upload_to='chat/attachments/')),
                ('attachment_size', models.CharField(default='', max_length=50)),
                ('attachment_type', models.CharField(default='', max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('seen', models.BooleanField(default=False)),
                ('sended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended', to=settings.AUTH_USER_MODEL)),
                ('sended_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recieved', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smerg_chat.room')),
            ],
        ),
    ]
